[package]
name = "use_case-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "1"
libfuzzer-sys = "0.4"
garde = { version = "0.22", features = ["derive", "email"] }

[dependencies.use_case]
path = ".."

[workspace]

[[bin]]
name = "create_user_input"
path = "fuzz_targets/create_user_input.rs"
test = false
doc = false
bench = false

[[bin]]
name = "login_input"
path = "fuzz_targets/login_input.rs"
test = false
doc = false
bench = false
